CREATE TABLE Astronaut(
AstroID INT,
Name VARCHAR(100),
PRIMARY KEY (AstroID)
) ;

-- CREATE TABLE AstronautShipment(
-- AstroID INT,
-- Invoice# INT,
-- PRIMARY KEY (AstroID, Invoice#),
-- FOREIGN KEY (AstroID) REFERENCES Astronaut(AstroID)
-- ON DELETE NO ACTION
-- ON UPDATE CASCADE,
-- FOREIGN KEY (Invoice#) REFERENCES ConfirmedShipment(Invoice#)
-- ON DELETE CASCADE
-- ON UPDATE NO ACTION
-- ) ;

CREATE TABLE Crew(
AstroID INT,
CompanyID INT,
PRIMARY KEY (AstroID),
FOREIGN KEY (AstroID) REFERENCES Astronaut(AstroID)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
ON DELETE SET NULL
ON UPDATE CASCADE
) ;

CREATE TABLE CrewShipment(
AstroID INT NOT NULL,
Invoice# INT NOT NULL,
PRIMARY KEY (AstroID, Invoice#),
FOREIGN KEY (AstroID) REFERENCES Crew(AstroID)
ON DELETE NO ACTION
ON UPDATE CASCADE,
FOREIGN KEY (Invoice#) REFERENCES ConfirmedShipment(Invoice#)
ON DELETE CASCADE
ON UPDATE NO ACTION
) ;

CREATE TABLE Passenger(
AstroID INT NOT NULL,
RequiresAssistance CHAR(3),
PRIMARY KEY (AstroID),
FOREIGN KEY (AstroID) REFERENCES Astronaut(AstroID)
ON DELETE CASCADE
ON UPDATE NO ACTION
) ;

CREATE TABLE Officer(
AstroID INT NOT NULL,
PRIMARY KEY (AstroID),
FOREIGN KEY (AstroID) REFERENCES Astronaut(AstroID)
ON DELETE CASCADE
ON UPDATE NO ACTION
) ;

-- CREATE TABLE OfficerReserveShipment(
-- AstroID INT,
-- Invoice# INT,
-- Date DATE,
-- PRIMARY KEY (Invoice#),
-- FOREIGN KEY (AstroID) REFERENCES Officer(AstroID)
-- ON DELETE NO ACTION
-- ON UPDATE NO ACTION,
-- FOREIGN KEY (Invoice#) REFERENCES ConfirmedShipment(Invoice#)
-- ON DELETE CASCADE
-- ON UPDATE NO ACTION
-- ) ;

CREATE TABLE Company(
CompanyID INT,
Name VARCHAR(100),
PRIMARY KEY (CompanyID)
) ;

CREATE TABLE Rocket(
RocketID INT,
Model VARCHAR(100) NOT NULL,
Capacity Double,
CompanyID INT,
PRIMARY KEY (RocketID),
FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
ON DELETE SET NULL
ON UPDATE NO ACTION
) ;

CREATE TABLE Reservation(
ReserveID INT NOT NULL,
RequestedDate DATE,
isDeparture BIT,
CompanyID INT NOT NULL,
RocketID INT NOT NULL,
PRIMARY KEY (ReserveID),
FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
FOREIGN KEY (RocketID) REFERENCES Rocket(RocketID)
ON DELETE NO ACTION
ON UPDATE NO ACTION
) ;

CREATE TABLE ShipmentLaunchpadSlot(
Invoice# INT,
ReserveID INT,
CargoID INT,
Cost REAL,
AstroID  INT,
Location VARCHAR(100),
Port# INT,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
StartTime REAL NOT NULL,
EndTime REAL NOT NULL,
PRIMARY KEY (Invoice#),
FOREIGN KEY (ReserveID) REFERENCES Reservation(ReserveID)
ON DELETE CASCADE
ON UPDATE NO ACTION,
FOREIGN KEY (CargoID) REFERENCES Cargo(CargoID)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
FOREIGN KEY (AstroID) REFERENCES Officer(AstroID)
ON DELETE NO ACTION
ON UPDATE CASCADE,
FOREIGN KEY (Port#, Location, StartDate, EndDate, StartTime, EndTime) REFERENCES Launchpad(Port#, Location, StartDate, EndDate, StartTime, EndTime)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
) ;

-- CREATE TABLE Launchpad(
-- Port# INT,
-- Location VARCHAR(100)
-- PRIMARY KEY (Port#, Location)
-- ) ;

CREATE TABLE LaunchpadSlot(
-- SlotID INT,
Location VARCHAR(100),
Port# INT,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
StartTime REAL NOT NULL,
EndTime REAL NOT NULL,
PRIMARY KEY (Location, Port#, StartDate, EndDate, StartTime, EndTime)
) ;

-- CREATE TABLE ShipmentLaunchpadSlot(
-- Invoice# INT,
-- Port# INT,
-- Location VARCHAR(100),
-- SlotID INT,
-- Cost REAL,
-- PRIMARY KEY (Invoice#),
-- UNIQUE (Port#, Location, SlotID),
-- FOREIGN KEY (Invoice#) REFERENCES ConfirmedShipment(Invoice#)
-- ON DELETE CASCADE
-- ON UPDATE CASCADE,
-- FOREIGN KEY (Port#, Location) REFERENCES Launchpad(Port#, Location)
-- ON DELETE NO ACTION
-- ON UPDATE NO ACTION,
-- FOREIGN KEY (SlotID) REFERENCES AvailabilitySlot(SlotID)
-- ON DELETE NO ACTION
-- ON UPDATE NO ACTION
-- ) ;

CREATE TABLE Cargo(
CargoID INT,
CargoType VARCHAR(100),
Weight INT,
Value INT,
CompanyID INT,
PRIMARY KEY (CargoID),
FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
ON DELETE SET NULL
ON UPDATE NO ACTION
) ;